
package Menu;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.platinum.CtaCorriente.acceso;

import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.event.ActionEvent;
import static com.platinum.CtaCorriente.acceso.id_usuario;
import static com.platinum.CtaCorriente.acceso.nombre_ejecutivo;


/**
 *
 * @author vari_
 */
public class Menu extends javax.swing.JFrame {
	private JTextField nombre_ejecutivo;
	private JTextField rut_ejecutivo;
	private JTextField departamento;
	
	
    
    public Menu() {
    	
    	setBackground(new Color(255, 255, 255));
    	setFont(new Font("Arial", Font.PLAIN, 18));
    	getContentPane().setBackground(new Color(119, 136, 153));
    	setTitle("Menu ejecutivo");
        initComponents();
        int id_usuario;
        
        id_usuario = acceso.id_usuario;
        try {
        	  
	          Connection conexion=DriverManager.getConnection("jdbc:mysql://localhost/banco","root" ,"");
	          Statement comando=conexion.createStatement();
        ResultSet ejecutivo = comando.executeQuery("SELECT * FROM ejecutivo WHERE id_usuario='"+id_usuario+"' ");
        String nombre_e;
        nombre_e = ejecutivo.getString("nombre");
        nombre_ejecutivo.setText(nombre_e);
        
        JOptionPane.showMessageDialog(null, nombre_e);
       
        } catch(SQLException ex){
	          
        }	        		 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        JLabel lblNewLabel = new JLabel("Nombre ejecutivo:");
        lblNewLabel.setForeground(new Color(255, 255, 255));
        lblNewLabel.setFont(new Font("Arial", Font.BOLD, 14));
        
        JLabel lblRut = new JLabel("Rut:");
        lblRut.setForeground(Color.WHITE);
        lblRut.setFont(new Font("Arial", Font.BOLD, 14));
        
        JLabel lblDepartamento = new JLabel("Departamento");
        lblDepartamento.setForeground(Color.WHITE);
        lblDepartamento.setFont(new Font("Arial", Font.BOLD, 14));
        
        nombre_ejecutivo = new JTextField();
        nombre_ejecutivo.setColumns(10);
      
        rut_ejecutivo = new JTextField();
        rut_ejecutivo.setColumns(10);
        
        departamento = new JTextField();
        departamento.setColumns(10);
        
        JButton salir = new JButton("Salir");
        
        salir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(36)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblDepartamento, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(departamento))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblRut, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(rut_ejecutivo, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(nombre_ejecutivo, GroupLayout.PREFERRED_SIZE, 284, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(426, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(525, Short.MAX_VALUE)
        			.addComponent(salir)
        			.addGap(288))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(45)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel)
        				.addComponent(nombre_ejecutivo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblRut, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
        				.addComponent(rut_ejecutivo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblDepartamento, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
        				.addComponent(departamento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(95)
        			.addComponent(salir)
        			.addContainerGap(222, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
}
